[package]
name = "hydroflow_plus_cli_integration"
publish = false
version = "0.5.0"
edition = "2021"

[features]
default = []
deploy = [ "hydro_deploy", "async-channel" ]

[dependencies]
stageleft = { path = "../../stageleft", version = "^0.1.0" }
hydroflow_plus = { path = "../../hydroflow_plus", version = "^0.5.0", features = [ "cli_integration" ] }
syn = { version = "2.0.0", features = [ "parsing", "extra-traits" ] }
tokio = { version = "1.16", features = [ "full" ] }
serde = { version = "1", features = [ "derive" ] }

hydro_deploy = { path = "../core", version = "^0.5.0", optional = true }
async-channel = { version = "1.8.0", optional = true }

[build-dependencies]
stageleft_tool = { path = "../../stageleft_tool", version = "^0.1.0" }
